version: "3.8"

services:
  nginx:
    image: nginx:latest
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
    ports:
      - "80:80"
    depends_on:
      - websocket
    networks:
      - draw-online-network

  websocket:
    image: nikkcom/draw-online:latest
    expose:
      - "8001"
    networks:
      - draw-online-networks

networks:
  draw-online-network:
    driver: bridge
