services:
  nginx:
    image: nginx:alpine
    container_name: draw-nginx
    ports:
      - "80:80"
     # - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - frontend
    networks:
      - app-net

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: draw-backend
    expose:
      - "8001"
    environment:
      - PYTHONUNBUFFERED=
    volumes:
      - ./backend:/app
    networks:
      - app-net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: draw-frontend
    expose:
      - "80"
    networks:
      - app-net
    restart: unless-stopped

networks:
  app-net:
    driver: bridge